ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

logging:
    level:
        root: INFO
        org.springframework: INFO
        io.subutai.bazaar: DEBUG


###
#   Message Broker Settings
###

spring:
  application:
    exchange: bazaar-exchange
    queue: bazaar-queue

  rabbitmq:
    hostname: rabbit-server
    username: hub
    password: change_me_in_production
