###
#   Ribbon Settings
###
ribbon:
  eureka:
    enabled: true

###
#   Discovery Settings
###
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

###
#   Logging Settings
###

logging:
    level:
        root: INFO
        org.springframework: INFO
        io.subutai.bazaar: DEBUG

###
#   Application Settings
###

spring:
  application:
    exchange: bazaar-exchange
    queue: bazaar-queue

###
#   RabbitMQ Settings
###

  rabbitmq:
    hostname: rabbit-server
    username: hub
    password: change_me_in_production

###
#   Database Settings
###

  datasource:
    url:  jdbc:h2:file:~/bazaar-query
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

###
#   Axon Settings
###

axon:
  distributed:
    enabled: true

